Time dependent Hamiltonian part 1
PierreGuilmin/torchqdynamics pull request #35
Opened 2023-03-24 14:51 UTC by abocquet

2023-03-25 11:07 UTC, PierreGuilmin commented
Can you motivate why we bring such machinery? I understand you want to propose a very general way to handle dependent-variables, but this is only needed in our case for `H` so I don't know if it justifies some dark magic. The `decorators.py` code will be especially hard to review/maintain, and I'm not sure why we need it. For example, what was not working with the previous much simpler implementation?

2023-03-27 07:22 UTC, abocquet commented
It's a matter of separation of concerns: we move the complexity of caching away from the logic of the solvers.
Once it's there adding caching is basically free so we avoid boilerplate and potential mistakes. 

I do agree that this code is not trivial but it's tested and should not move much in the future so it's fine to have that IMHO. If you insist we can going back but it would be a shame to, as now we have a tool that works well.

2023-03-27 16:54 UTC, gautierronan commented
> It's a matter of separation of concerns: we move the complexity of caching away from the logic of the solvers. Once it's there adding caching is basically free so we avoid boilerplate and potential mistakes.
> 
> I do agree that this code is not trivial but it's tested and should not move much in the future so it's fine to have that IMHO. If you insist we can going back but it would be a shame to, as now we have a tool that works well.

I agree it's nice to separate this kind of machinery from the main code, but I have mainly two concerns about your solution:

1. Readability. It's difficult to understand what's happening, especially for the poor physicist who just wants to know what's happening to it's time-dependent matrix under the hood. Readability is a big factor in people adopting the code. I know of a lot of theoreticians that do not use qutip because they don't know what's happening and they don't want to spend time going deep into the code to understand. Instead they use home-made solvers.
2. Performance. I'm concerned that this additional machinery may not bode well with pytorch, and especially with `torch.compile()`. This is in a very performance-sensitive part of the code, so I would argue that simpler is better. But it might not change anything, I'm not sure.

2023-03-27 17:57 UTC, PierreGuilmin requested changes
Here's a first review. Let's rebase this on `main` once we agree on the code, to take `H` batching and the file reorganization into account (it may be easier to open a new PR and manually copy-pasting the modifications). We also need to do the order Rouchon orders (but maybe it's coming next).

On another note, I understand the interest of a completely isolated little helper to cache functions depending on some variables, but let me advocate the following alternative option. The reason is that I think `H` is the only time-dependent object we will have, and that the caching is mostly going to be used for Rouchon methods, so I'm not sure if we need such a generic solution. Moreover, even if the option I propose is a tiny bit more manual, it really adds very little code and does not, IMO, affect features or readability.
<details>
  <summary>Alternative option (drafty)</summary>

  Add to `ForwardQSolver`:

  ```python
  def __init__(self, H):
      self._H = H

  def H(self, t):
      if isinstance(self._H, torch.Tensor):
          self._H_has_changed = False
          return self._H
      elif callable(self._H):
          self._H_has_changed = True
          return self._H(t)
      else:
          # will come in a next PR
          raise NotImplementedError('Piecewise constant Hamiltonian is not supported yet.')
  ```

  Add to `MERouchon`

  ```python
  def forward(self, t, dt, rho):
      """Compute rho(t+dt) using a Rouchon method of order 1."""
      rho = kraus_map(rho, self.Ms(t, dt))
      return rho / trace(rho)[..., None, None].real

  def Ms(self, t, dt):
      if not self._H_has_changed:
          return self._Ms

      # non-hermitian Hamiltonian at time t
      H_nh = self.H(t) - 0.5j * self.sum_nojump

      M0 = self.I - 1j * dt * H_nh
      self._Ms = torch.cat((M0[None, ...], sqrt(dt) * self.jump_ops))
      return self._Ms
  ```

</details>

2023-03-27 17:57 UTC, PierreGuilmin commented on torchqdynamics/decorators.py
So I won't review this file, I trust you 😉

2023-03-27 17:57 UTC, PierreGuilmin commented on torchqdynamics/mesolve.py
>          H_nh = self.H(t) - 0.5j * self.sum_nojump
This should be calculated once for non time-dependent tensors.

2023-03-29 09:58 UTC, abocquet commented
I agree your solution is simple enough so it's scalable. However for `dt`s that depend on time, you need to update `M0(H, dt)` on change of `H` or `dt`. It's still doable locally but it adds more potential bugs. We could also decide that for time-variable schemas we always recompute `M0`

2023-03-30 09:10 UTC, PierreGuilmin commented
That's a good point. I don't know whether adaptative solvers change their `dt` at each step or not. 🤷‍♂️

2023-04-03 10:17 UTC, closed without merging