Define a default progress bar format
PierreGuilmin/torchqdynamics pull request #55
Opened 2023-03-31 19:16 UTC by gautierronan

2023-04-01 09:15 UTC, abocquet commented
Nice initiative. To this point maybe we could directly code a `torchqdiffeq.tqdm` function that calls tqdm with the correct formatting to avoid copy pasting it everywhere and be easier to add more options later ?

2023-04-01 16:56 UTC, gautierronan commented
> Nice initiative. To this point maybe we could directly code a `torchqdynamics.tqdm` function that calls tqdm with the correct formatting to avoid copy pasting it everywhere and be easier to add more options later ?

Yes maybe something more like the last commit?

2023-04-01 17:42 UTC, abocquet submitted a review, later dismissed
Yes, this is exactly what I had in mind

2023-04-03 14:37 UTC, PierreGuilmin requested changes
Nice implem!

2023-04-03 14:37 UTC, PierreGuilmin commented on torchqdynamics/progressbar.py
Could we rename this file `progress_bar.py` to follow our naming convention?

2023-04-03 14:37 UTC, PierreGuilmin commented on torchqdynamics/progressbar.py
> +from tqdm.auto import tqdm as std_tqdm
I'm really not fan of the notebook progress bar viewer (too big and colorfull IMO, plus it doesn't work well with dark mode), could we switch to have the regular progress bar everywhere (`from tqdm import tqdm`)?

![Screenshot 2023-04-03 at 16 31 40](https://user-images.githubusercontent.com/38159029/229540877-b83d4802-9824-4fd2-9904-e6abe66af5bb.png)

2023-04-03 14:37 UTC, PierreGuilmin commented on torchqdynamics/progressbar.py
> +# Redefine tqdm with some default arguments
```suggestion
# redefine tqdm with some default arguments
```

2023-04-03 19:00 UTC, gautierronan commented
In the end I went with `|██████████| 100.0% - time 00:05/00:00`, and removed the `{desc}` since it's not implemented yet.

2023-04-04 09:30 UTC, merged