Various utility functions
PierreGuilmin/torchqdynamics pull request #57
Opened 2023-04-01 22:11 UTC by gautierronan

This PR introduces a bunch of basic utility functions, both for operator and state initialization. Nothing particulary difficult. While reviewing, mostly check if you agree with the naming conventions and the behavior of the various functions introduced.

2023-04-03 13:20 UTC, abocquet submitted a review, later dismissed

2023-04-08 01:29 UTC, gautierronan commented
By mistake I added commit https://github.com/PierreGuilmin/torchqdynamics/pull/57/commits/cb35a45e434ac00e924c69955b31bafc2f4b45b7 to this PR instead of another PR. It's just the typing update to 3.10 annotations, so I guess it's simple enough. Not sure how to revert properly so I keep it inside this PR.

2023-04-11 09:06 UTC, PierreGuilmin requested changes
Amazing PR thank you 🤩  The new typing annotations are so much easier to read, and we can finally write examples and tests with our own functions 👏

Concerning the `dtype` and `device` arguments, I think we should remove them everywhere. The best way IMO not to clutter the code would be to make a decorator, but anyway I think we should rather use and advertise the global functions `set_default_device` and `set_default_tensor_type` rather than annoying ourselves everywhere with devices and types.

2023-04-11 09:06 UTC, PierreGuilmin commented on torchqdynamics/operators.py
> +    """Pauli raising operator."""
```suggestion
    """Pauli raising operator $\sigma_+$."""
```
Same for lowering.

2023-04-11 09:06 UTC, PierreGuilmin commented on torchqdynamics/operators.py
> +    return torch.eye(dim, dtype=dtype, device=device)
For example, after the proposed changes:
```suggestion
def qeye(*dims: int) -> Tensor:
    """Identity operator."""
    return torch.eye(prod(dims))
```

2023-04-11 09:06 UTC, PierreGuilmin commented on torchqdynamics/operators.py
> +    return torch.eye(dim, dtype=dtype, device=device)
Should we call this guy `eye` directly or `identity`? I never liked `qeye`.

2023-04-11 09:06 UTC, PierreGuilmin commented on torchqdynamics/operators.py
> +    space given by the product of all dimensions.
Same, is this really a needed feature? We can build all of these very easily with `tensprod` and it's more readable IMO.

2023-04-11 09:06 UTC, PierreGuilmin commented on torchqdynamics/operators.py
> +    """Single-mode displacement operator."""
```suggestion
    """Displacement operator."""
```
I think it's always single mode by default, no need to precise it everywhere.

2023-04-16 23:15 UTC, gautierronan commented on torchqdynamics/states.py
> +    """
I think it's a neat feature which I personnaly like using. People can still use your version if they prefer. Especially for the annihilation operators, I really like
```
a, b, c = tq.destroy(Na, Nb, Nc)
```
which is way shorter and readable than
```
ia_ = tq.eye(Na)
ib_ = tq.eye(Nb)
ic_ = tq.eye(Nc)
a_ = tq.destroy(Na)
b_ = tq.destroy(Nb)
c_ = tq.destroy(Nc)
a = tq.tensprod(a_, ib_, ic_)
b = tq.tensprod(ia_, b_, ic_)
c = tq.tensprod(ia_, ib_, c_)
```
(which is literally what I do with qutip personnaly)

2023-04-17 10:27 UTC, PierreGuilmin requested changes
Minor comments.

2023-04-17 10:27 UTC, PierreGuilmin commented on torchqdynamics/operators.py
> +    return torch.diag(torch.sqrt(torch.arange(1, dim, device=device)), 1).to(dtype)
```suggestion
    return torch.arange(1, dim, device=device).sqrt().diag(1).to(dtype)
```

2023-04-17 10:27 UTC, PierreGuilmin commented on torchqdynamics/operators.py
> +    return torch.diag(torch.sqrt(torch.arange(1, dim, device=device)), 1).to(dtype)
Same for `_create_single`.

2023-04-17 10:27 UTC, PierreGuilmin commented on torchqdynamics/operators.py
> +    return tuple(ops)
Here's a refinement (also work for a single operator):
```python
a = [_destroy_single(dim, dtype=dtype, device=device) for dim in dims]
I = [eye(dim, dtype=dtype, device=device) for dim in dims]
return (tq.tensprod(*[I[i] if i != j else a[j] for j in range(len(dims))]) for i in range(len(dims)))
```

2023-04-17 10:28 UTC, PierreGuilmin commented
I will make a subsequent PR to fix the repeated `dtype` and `device` by using a decorator. It will also set the correct default complex type using `torch.get_default_dtype` rather than overriding it by default. No need to change anything in this PR.

2023-04-17 15:12 UTC, PierreGuilmin approved these changes

2023-04-17 16:10 UTC, merged