Some more renaming and reorganization
pierreguilmin/torchqdynamics pull request #75
Opened 2023-04-24 19:29 UTC by gautierronan

Following up on https://github.com/pierreguilmin/torchqdynamics/pull/73, this PR proposes a few renamings and mostly a folder reorganization.

- f69a992cfc6c5b8a76c92de3ddf90feda7582ee8 and 01d568bec411092ee2d1c57b8fcc986ff99c5984: Rename test files and test classes for consistency with the library.
- 78bc0c8a4d6a2236e9f27ae6d3d961396e966f2f: Separate files into three new folders: utils (all utility functions), smesolve, and ode (all ode integration functions). I kept `options.py` and `solver.py` in the main folder.
- 9b673facf1237aec5dd586c9f45b5a64ddeaf128: Rename the files to remove "ode" (since it's now in the folder of the same name), and renamed the `AdaptiveODESolver` class to `AdapativeODEIntegrator` to differentiate it from the actual `Solver` class.

2023-04-24 20:12 UTC, pierreguilmin requested changes
Very nice!! Much cleaner ✨

2023-04-24 20:12 UTC, pierreguilmin commented on torchqdynamics/ode/forward_solver.py
The file name should match the class name, I think we can use `ForwardSolver` and `forward_solver.py` because they are in the `ode` namespace so it's clear enough 👍

2023-04-24 20:12 UTC, pierreguilmin commented on torchqdynamics/ode/adaptive_integrator.py
>      """A parent class for all adaptive time step ODE solvers.
```suggestion
    """A parent class for all adaptive time step ODE integrators.
```

2023-04-24 20:12 UTC, pierreguilmin commented on torchqdynamics/ode/adjoint_solver.py
Let's consistently use the term `integrate` for the ODE solving, line 138
```diff
- # solve the ODE forward without storing the graph of operations
+ # integrate the ODE forward without storing the graph of operations
```

2023-04-25 08:00 UTC, pierreguilmin commented on tests/mesolve/test_mesolve.py
I suggest renaming back to `me_solver_test.py` and `MESolverTest`:
- The file name conflicts with the future test file for the real `mesolve.py` file (testing the API, the errors, the arguments conversion, etc...).
- Pytest collects by default all files beginning by `test_...` and all classes beginning by `Test...`, so when we write a base class for some tests (like this one) or some helpers for other tests (like `open_system.py`), it's better to use a different naming. This naming convention also makes very clear for a reader what are the test files and what are the files used to build the tests that are not themselves testing anything. Typically we will have in the `tests/` directory some random files (`utils.py`, `open_system.py`, `me_solver_test.py`, ...) and some files beginning by `test_` and suffixed with a file name from the package (`test_euler.py`, test_mesolve.py`, etc...).

2023-04-25 17:53 UTC, gautierronan commented on tests/mesolve/test_mesolve.py
I get your point, but I then I think `MESolverTest` sounds like a test whereas it is a base class for actual test classes. Anyway, I renamed to `MESolverTester` in this case, which I think it a bit more explicit.

2023-04-25 20:46 UTC, merged