Add batching manager
pierreguilmin/torchqdynamics pull request #80
Opened 2023-04-28 14:16 UTC by abocquet

Paves the way for proper handling of the batching in https://github.com/pierreguilmin/torchqdynamics/pull/58. Indeed, when we add time dependent operators, following the dimensions becomes necessary, hence the `BatchingHandler` class

It'll also avoid duplicate code for next numerical schemas (e.g SMESolve)

2023-04-28 16:26 UTC, pierreguilmin commented on torchqdynamics/batching.py
> +class BatchingHandler:
Also the file name should match the class name.

2023-04-28 16:27 UTC, pierreguilmin commented on torchqdynamics/batching.py
> +        """Batches H and the state (psi or rho)"""
```suggestion
        """Batches H and the state (psi or rho)."""
```

2023-04-28 16:29 UTC, pierreguilmin commented on torchqdynamics/batching.py
> +class BatchingHandler:
And then we can add the `t_save` conversion as well.

2023-04-28 16:31 UTC, pierreguilmin commented on torchqdynamics/batching.py
> +        self, H: TDOperatorLike, state: OperatorLike, state_to_dm=False
Also fix the typing of `__init__` and `unbatch`.

2023-04-28 19:17 UTC, gautierronan reviewed
Really nice PR @abocquet. I love it ! I don't have any more comments than what @pierreguilmin already proposed :)

2023-04-29 18:22 UTC, gautierronan commented on torchqdynamics/mesolve/mesolve.py
> +    exp_save = formatter.unbatch(exp_save)
Found a small bug (already present in the previous code, but it's a good PR to fix it). If no `exp_ops` are passed, then `exp_save` is None, and this raises an error. So we need to check if `exp_save` is not None somewhere.

Same thing for `sesolve`.

2023-05-01 19:52 UTC, abocquet commented on torchqdynamics/batching.py
> +class BatchingHandler:
But `t_save` isn't batched is it?

2023-05-02 08:29 UTC, pierreguilmin commented on torchqdynamics/tensor_formatter.py
> +    def __init__(self, dtype, device):
Typing missing.

2023-05-02 08:30 UTC, pierreguilmin commented on torchqdynamics/tensor_formatter.py
> +    def unbatch(self, save: Optional[Tensor]):
Please use `Tensor | None`.

2023-05-02 08:33 UTC, pierreguilmin requested changes
Nitpicking.

2023-05-02 09:48 UTC, pierreguilmin commented on torchqdynamics/tensor_formatter.py
> +    def unbatch(self, save: Tensor | None):
Also
```suggestion
    def unbatch(self, save: Tensor | None) -> Tensor | None:
```

2023-05-02 09:50 UTC, pierreguilmin commented
You need a `from __future__ import annotations` to fix the CI.

2023-05-02 14:25 UTC, pierreguilmin approved these changes

2023-05-02 14:26 UTC, merged